version: "2"

exclude_patterns:
  - docs/style.md
  - src/migration/
  - vendor/

plugins:
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          mass_threshold: 125 # avoid increasing, increments of 5
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
  tslint:
    enabled: true
    config: config/tslint.cc.json