version: "2"

engines:
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          mass_threshold: 60

plugins:
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
  tslint:
    enabled: true
    config: config/tslint.cc.json