build:
  image: apextoaster/node:master
  stage: build
  tags:
    - runner:k8s

  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - ssh-keyscan git.apextoaster.com >> ~/.ssh/known_hosts
  script:
    - yarn
    - make strict

  artifacts:
    expire_in: 1 week
    paths:
      - out/coverage
      - out/docs
      - out/main-bundle.*
      - out/version.json
