build:
  image: apextoaster/node:master
  stage: build
  tags:
    - runner:k8s

  script:
    - git submodule init
    - git submodule update
    - yarn
    - make strict

  artifacts:
    expire_in: 1 week
    paths:
      - out/coverage
      - out/docs
      - out/main-bundle.*
      - out/version.json
