apiVersion: v1
kind: Service
metadata:
  name: isolex
  labels:
    k8s-app: isolex
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: http
  selector:
    k8s-app: isolex