metadata:
  kind: kubernetes-apps-controller
  name: test-k8s-apps
data:
  context:
    default: true
  default:
    namespace: default
  filters:
    - metadata:
        kind: command-filter
        name: k8s_test_filter
      data:
        match:
          rules:
            - key: labels.test_k8s
              operator: any
              values:
                - string: test
  redirect:
    defaults: {}
    forces: {}
  transforms:
    - metadata:
        kind: template-transform
        name: k8s_deployment_scale
      data:
        filters:
          - metadata:
              kind: command-filter
              name: test-k8s-app-scale
            data:
              match:
                rules:
                  - key: verb
                    operator: any
                    values:
                      - string: update
        templates:
          body: >-
            {{ data.selector }}: {{ data.replicas }}
    - metadata:
        kind: template-transform
        name: k8s_deployment_list
      data:
        filters:
          - metadata:
              kind: command-filter
              name: test-k8s-app-list
            data:
              match:
                rules:
                  - key: verb
                    operator: any
                    values:
                      - string: list
        templates:
          body: >-
            {{#each data}}
              {{ metadata.name }}: {{ spec.replicas }}
            {{/each}}
    - metadata:
        kind: flatten-transform
        name: k8s-deployment-flatten
      data:
        join: ""
        keys: [$.data.body]