metadata:
  kind: kubernetes-core-controller
  name: test-k8s-core
data:
  context:
    default: true
  default:
    namespace: default
  filters:
    - metadata:
        kind: command-filter
        name: k8s_test_filter
      data:
        match:
          rules:
            - key: labels.test_k8s
              operator: any
              values:
                - string: test
  transforms:
    - metadata:
        kind: template-transform
        name: k8s_pod_names
      data:
        templates:
          body: >-
            {{#each data}}
              {{this.metadata.name}}: {{this.status.phase}}
            {{/each}}
    - metadata:
        kind: flatten-transform
        name: k8s_body_flatten
      data:
        join: ""
        keys: [$.data.body]