---

# example config

bot:
  filter:
    user:
      ignore:
        - 1
        - name

  handler:
    echo:
      pattern: >-
        @{{cmd.from.userName}}: {{cmd.data.message}} ({{cmd.name}})

  log:
    level: debug
    name: isolex

  parser:
    lex:
      bot:
        name: isolex
        alias: test
      account:
        accessKey: ADECBA
        secretKey: 123/abc
      region: us-east-1
      tags:
        - '--lex'

    yaml:
      tags:
        - '--json'
        - '--yaml'

  stack:
    account:
      email: yourname@email.com
      password: 'pass$word'
    delay:
      next: 100
      rate: 2000
    rooms: [1, 17]

