---

# example config

bot:
  aws:
    lex:
      bot:
        name: isolex
        alias: test
      account:
        accessKey: AKIAABCDEFGH
        secretKey: 12334567890/abcdefghijklmnop
      region: us-east-1
  log:
    level: debug
    name: isolex
  stack:
    account:
      email: yourname@email.com
      password: password
    rooms: [1, 17]

