---

metadata:
  kind: bot
  name: isolex
data:
  filters:
    - metadata:
        kind: user-filter
        name: ignore-bots
      data:
        mode: exclude
        data:
          - isolex
          - isolex-test
  controllers:
    - !include ../docs/controller/completion-controller.yml
    - !include ../docs/controller/kubernetes-controller.yml
    - !include ../docs/controller/math-controller.yml
    - !include ../docs/controller/search-controller-mdn.yml
    - !include ../docs/controller/sed-controller.yml
    - !include ../docs/controller/session-controller.yml
    - !include ../docs/controller/token-controller.yml
    - !include ../docs/controller/user-controller.yml
    - !include ../docs/controller/weather-controller-owm.yml
  listeners:
    - !include ../docs/listener/discord-listener.yml
    - !include ../docs/listener/express-listener.yml
    - !include ../docs/listener/slack-listener.yml
  logger:
    level: debug
    name: isolex
  migrate: true
  parsers:
    - !include ../docs/parser/args-parser.yml
    - !include ../docs/parser/args-parser-complete.yml
    - !include ../docs/parser/args-parser-join.yml
    - !include ../docs/parser/args-parser-login.yml
    - !include ../docs/parser/args-parser-k8s.yml
    - !include ../docs/parser/lex-parser.yml
    - !include ../docs/parser/yaml-parser.yml
  storage:
    type: sqlite
    database: "./out/isolex.db"
