$schema: "http://json-schema.org/schema#" # yes, this is a json schema written in yaml
$id: "https://github.com/ssube/isolex/schema.yml"
definitions:
  entity-command:
    type: object
    additionalProperties: true
    properties:
      noun:
        type: string
      verb:
        type: string

  entity-context:
    type: object
    additionalProperties: true
    properties:
      channel:
        $ref: "#/definitions/entity-context-channel"
      name:
        type: string
      uid:
        type: string

  match-rule:
    type: object
    additionalProperties: false
    properties:
      key:
        type: string
      negate:
        type: boolean
      operator:
        enum: [any, every]
      values:
        type: array
        items:
          type: object
          anyOf:
            - properties:
                string:
                  type: string
            - properties:
                regexp:
                  type: string
  match-data:
    type: object
    additionalProperties: false
    properties:
      rules:
        type: array
        items:
          $ref: "#/definitions/match-rule"

  match-results:
    type: object
    additionalProperties: false
    properties:
      matched:
        type: boolean
    errors:
      type: array
      items:
        type: string

  service-controller:
    type: object
    properties:
      filters:
        type: array
        items:
          $ref: "#/definitions/service-definition"
      transforms:
        type: array
        items:
          $ref: "#/definitions/service-definition"

  service-controller-count:
    allOf:
      - $ref: "#/definitions/service-controller"
      - type: object
        properties:
          default:
            type: object
            additionalProperties: false
            properties:
              count:
                type: string
              name:
                type: string
          field:
            type: object
            additionalProperties: false
            properties:
              count:
                type: string
              name:
                type: string
          range:
            type: object
            additionalProperties: false
            properties:
              min:
                type: number
              max:
                type: number

  service-controller-kubernetes:
    allOf:
      - $ref: "#/definitions/service-controller"
      - type: object
        properties:
          context:
            type: object
            additionalProperties: false
            properties:
              cluster:
                type: string
              default:
                type: string
              path:
                type: string
          default:
            type: object
            additionalProperties: false
            properties:
              namespace:
                type: string

  service-controller-math:
    allOf:
      - $ref: "#/definitions/service-controller"
      - type: object
        properties:
          format:
            type: object
            additionalProperties: false
            properties:
              list:
                type: object
                additionalProperties: false
                properties:
                  join:
                    type: string
              number:
                type: object
                additionalProperties: false
                properties:
                  notation:
                    enum: [fixed, exponential, engineering, auto]
                  precision:
                    type: number
                  lowerExp:
                    type: number
                  upperExp:
                    type: number
                  fraction:
                    type: string
              node:
                type: object
                additionalProperties: false
                properties:
                  implicit:
                    type: string
                  parenthesis:
                    type: string
          math:
            type: object
            additionalProperties: false
            properties:
              matrix:
                type: string
              number:
                type: string

  service-parser:
    type: object
    properties:
      defaultCommand:
        $ref: "#/definition/entity-command"
      preferData:
        type: boolean
      match:
        $ref: "#/definitions/match-data"
 
  service-parser-lex:
    allOf:
      - $ref: "#/definitions/service-controller"
      - type: object
        properties:
          account:
            type: object
            additionalProperties: false
            properties:
              accessKey:
                type: string
              secretKey:
                type: string
          bot:
            type: object
            additionalProperties: false
            properties:
              alias:
                type: string
              name:
                type: string
              region:
                type: string
 
  service-definition:
    type: object
    additionalProperties: false
    required: [data, metadata]
    properties:
      data:
        type: object
      metadata:
        $ref: "#/definitions/service-metadata"
 
  service-metadata:
    type: object
    additionalProperties: false
    required: [kind, name]
    properties:
      kind:
        type: string
      name:
        type: string

# root
type: object
additionalProperties: false
properties:
  metadata:
    $ref: "#/definitions/service-metadata"
  data:
    type: object
    properties:
      data:
        type: object
        properties:
          controllers:
            type: array
            items:
              allOf:
                - $ref: "#/definitions/service-definition"
                - type: object
                  properties:
                    data:
                      oneOf:
                        - $ref: "#/definitions/service-controller-count"
                        - $ref: "#/definitions/service-controller-kubernetes"
                        - $ref: "#/definitions/service-controller-math"
          filters:
            type: array
            items:
              allOf:
                - $ref: "#/definitions/service-definition"
          listeners:
            type: array
            items:
              allOf:
                - $ref: "#/definitions/service-definition"
          logger:
            type: object
            properties:
              level:
                enum: [debug, info, warn, error]
              name:
                type: string
          migrate:
            type: boolean
          parsers:
            type: array
            items:
              allOf:
                - $ref: "#/definitions/service-definition"
                - type: object
                  properties:
                    data:
                      oneOf:
                        - $ref: "#/definitions/service-parser-lex"
          storage:
            type: object
            properties:
              database:
                type: string
              type:
                type: string