$schema: "http://json-schema.org/schema#" # yes, this is a json schema written in yaml
$id: "https://github.com/ssube/isolex/schema.yml"
definitions:
  array-mapper:
    type: object
    additionalProperties: true
    properties:
      rest:
        type: string
      skip:
        type: number
      take:
        type: array
        items:
          type: string
 
  checklist:
    type: object
    additionalProperties: true
    properties:
      data:
        type: array
        items:
          type: string
      mode:
        enum: [exclude, include]

  entity-command:
    type: object
    additionalProperties: true
    properties:
      noun:
        type: string
      verb:
        type: string

  entity-context:
    type: object
    additionalProperties: true
    properties:
      channel:
        $ref: "#/definitions/entity-context-channel"
      name:
        type: string
      uid:
        type: string

  match-rule:
    type: object
    additionalProperties: false
    properties:
      key:
        type: string
      negate:
        type: boolean
      operator:
        enum: [any, every]
      values:
        type: array
        items:
          type: object
          anyOf:
            - properties:
                string:
                  type: string
            - properties:
                regexp:
                  type: string
  match-data:
    type: object
    additionalProperties: false
    properties:
      rules:
        type: array
        items:
          $ref: "#/definitions/match-rule"

  match-results:
    type: object
    additionalProperties: false
    properties:
      matched:
        type: boolean
    errors:
      type: array
      items:
        type: string

  service-bot:
    type: object
    properties:
      controllers:
        type: array
        items:
          allOf:
            - $ref: "#/definitions/service-definition"
            - type: object
              properties:
                data:
                  anyOf:
                    - $ref: "#/definitions/service-controller-completion"
                    - $ref: "#/definitions/service-controller-count"
                    - $ref: "#/definitions/service-controller-dice"
                    - $ref: "#/definitions/service-controller-echo"
                    - $ref: "#/definitions/service-controller-kubernetes"
                    - $ref: "#/definitions/service-controller-learn"
                    - $ref: "#/definitions/service-controller-math"
                    - $ref: "#/definitions/service-controller-random"
                    - $ref: "#/definitions/service-controller-search"
                    - $ref: "#/definitions/service-controller-sed"
                    - $ref: "#/definitions/service-controller-session"
                    - $ref: "#/definitions/service-controller-token"
                    - $ref: "#/definitions/service-controller-user"
                    - $ref: "#/definitions/service-controller-weather"
      filters:
        type: array
        items:
          allOf:
            - $ref: "#/definitions/service-definition"
      listeners:
        type: array
        items:
          allOf:
            - $ref: "#/definitions/service-definition"
      logger:
        type: object
        properties:
          level:
            enum: [debug, info, warn, error]
          name:
            type: string
      migrate:
        type: boolean
      parsers:
        type: array
        items:
          allOf:
            - $ref: "#/definitions/service-definition"
            - type: object
              properties:
                data:
                  anyOf:
                    - $ref: "#/definitions/service-parser-args"
                    - $ref: "#/definitions/service-parser-echo"
                    - $ref: "#/definitions/service-parser-lex"
                    - $ref: "#/definitions/service-parser-regex"
                    - $ref: "#/definitions/service-parser-split"
                    - $ref: "#/definitions/service-parser-yaml"
      storage:
        type: object
        properties:
          database:
            type: string
          type:
            type: string

  service-controller:
    type: object
    properties:
      filters:
        type: array
        items:
          $ref: "#/definitions/service-definition"
      transforms:
        type: array
        items:
          $ref: "#/definitions/service-definition"
  service-controller-completion:
    $ref: "#/definitions/service-controller"
  service-controller-count:
    allOf:
      - $ref: "#/definitions/service-controller"
      - type: object
        properties:
          default:
            type: object
            additionalProperties: false
            properties:
              count:
                type: string
              name:
                type: string
          field:
            type: object
            additionalProperties: false
            properties:
              count:
                type: string
              name:
                type: string
          range:
            type: object
            additionalProperties: false
            properties:
              min:
                type: number
              max:
                type: number
  service-controller-dice:
    $ref: "#/definitions/service-controller"
  service-controller-echo:
    $ref: "#/definitions/service-controller"
  service-controller-kubernetes:
    allOf:
      - $ref: "#/definitions/service-controller"
      - type: object
        properties:
          context:
            type: object
            additionalProperties: false
            properties:
              cluster:
                type: boolean
              default:
                type: boolean
              path:
                type: string
          default:
            type: object
            additionalProperties: false
            properties:
              namespace:
                type: string
  service-controller-learn:
    allOf:
      - $ref: "#/definitions/service-controller"
      - type: object
        properties:
          field:
            type: string
          nouns:
            $ref: "#/definitions/checklist"
  service-controller-math:
    allOf:
      - $ref: "#/definitions/service-controller"
      - type: object
        properties:
          format:
            type: object
            additionalProperties: false
            properties:
              list:
                type: object
                additionalProperties: false
                properties:
                  join:
                    type: string
              number:
                type: object
                additionalProperties: false
                properties:
                  notation:
                    enum: [fixed, exponential, engineering, auto]
                  precision:
                    type: number
                  lowerExp:
                    type: number
                  upperExp:
                    type: number
                  fraction:
                    type: string
              node:
                type: object
                additionalProperties: false
                properties:
                  implicit:
                    type: string
                  parenthesis:
                    type: string
          math:
            type: object
            additionalProperties: false
            properties:
              matrix:
                type: string
              number:
                type: string
  service-controller-random:
    $ref: "#/definitions/service-controller"
  service-controller-search:
    allOf:
      - $ref: "#/definitions/service-controller"
      - type: object
        properties:
          count:
            type: number
          field:
            type: string
          request:
            type: object
            additionalProperties: false
            properties:
              method:
                type: string
              url:
                type: string
 
  service-controller-sed:
    $ref: "#/definitions/service-controller"
  service-controller-session:
    $ref: "#/definitions/service-controller"
  service-controller-time:
    allOf:
      - $ref: "#/definitions/service-controller"
      - type: object
        properties:
          locale:
            type: string
          zone:
            type: string
  service-controller-token:
    $ref: "#/definitions/service-controller"
  service-controller-user:
    $ref: "#/definitions/service-controller"
  service-controller-weather:
    allOf:
      - $ref: "#/definitions/service-controller"
      - type: object
        properties:
          api:
            type: object
            additionalProperties: false
            properties:
              key:
                type: string
              root:
                type: string

  service-filter-rule:
    type: object
    properties:
      match:
        $ref: "#/definitions/match-data"
  service-filter-user:
    type: object
    properties:
      users:
        $ref: "#/definitions/checklist"

  service-listener-discord:
    type: object
    properties:
      presence:
        type: object
      token:
        type: string
  service-listener-express:
    type: object
    properties:
      expose:
        type: object
        properties:
          graph:
            type: boolean
          graphiql:
            type: boolean
          metrics:
            type: boolean
      graph:
        $ref: "#/definitions/service-definition"
      listen:
        type: object
        properties:
          address:
            type: string
          port:
            type: number
      token:
        type: object
        properties:
          audience:
            type: string
          issuer:
            type: string
          scheme:
            type: string
          secret:
            type: string
  service-listener-slack:
    type: object
    properties:
      token:
        type: object
        properties:
          bot:
            type: string
          web:
            type: string

  service-parser:
    type: object
    properties:
      defaultCommand:
        $ref: "#/definitions/entity-command"
      preferData:
        type: boolean
      match:
        $ref: "#/definitions/match-data"
  service-parser-args:
    allOf:
      - $ref: "#/definitions/service-parser"
      - type: object
        properties:
          args:
            type: object
            properties:
              array:
                type: array
                items:
                  type: string
              boolean:
                type: array
                items:
                  type: string
              configuration:
                type: object
              count:
                type: array
                items:
                  type: string
              default:
                type: array
                items:
                  type: string
              number:
                type: array
                items:
                  type: string
              required:
                type: array
                items:
                  type: string
              string:
                type: array
                items:
                  type: string
              "--":
                type: boolean
  service-parser-echo:
    allOf:
      - $ref: "#/definitions/service-parser"
      - type: object
        properties:
          dataMapper:
            $ref: "#/definitions/array-mapper"
  service-parser-lex:
    allOf:
      - $ref: "#/definitions/service-parser"
      - type: object
        properties:
          account:
            type: object
            additionalProperties: false
            properties:
              accessKey:
                type: string
              secretKey:
                type: string
          bot:
            type: object
            additionalProperties: false
            properties:
              alias:
                type: string
              name:
                type: string
              region:
                type: string
  service-parser-regex:
    allOf:
      - $ref: "#/definitions/service-parser"
      - type: object
        properties:
          dataMapper:
            $ref: "#/definitions/array-mapper"
          regexp:
            type: string
  service-parser-split:
    allOf:
      - $ref: "#/definitions/service-parser"
      - type: object
        properties:
          dataMapper:
            $ref: "#/definitions/array-mapper"
          every:
            type: boolean
          split:
            type: object
 
  service-parser-yaml:
    $ref: "#/definitions/service-parser"
 
  service-transform:
    type: object
    properties:
      parsers:
        type: array
        items:
          allOf:
            - $ref: "#/definitions/service-definition"
            - $ref: "#/definitions/service-parser"
  service-transform-flatten:
    allOf:
      - $ref: "#/definitions/service-transform"
      - type: object
        properties:
          deep:
            type: boolean
          join:
            type: string
          keys:
            type: array
            items:
              type: string
  service-transform-jsonpath:
    allOf:
      - $ref: "#/definitions/service-transform"
      - type: object
        properties:
          queries:
            type: object
            additionalProperties:
              type: string
  service-transform-template:
    allOf:
      - $ref: "#/definitions/service-transform"
      - type: object
        properties:
          templates:
            type: object
            additionalProperties:
              type: string
 
  service-graph:
    type: object
  service-definition:
    type: object
    additionalProperties: false
    required: [data, metadata]
    properties:
      data:
        type: object
      metadata:
        $ref: "#/definitions/service-metadata"
  service-metadata:
    type: object
    additionalProperties: false
    required: [kind, name]
    properties:
      kind:
        type: string
      name:
        type: string

  utils-cooldown:
    type: object
    additionalProperties: false
    properties:
      base:
        type: number
      grow:
        type: number

# root
type: object
additionalProperties: false
required: [data, metadata]
properties:
  metadata:
    $ref: "#/definitions/service-metadata"
  data:
    $ref: "#/definitions/service-bot"